/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Voucher = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'redeemed' : IDL.Bool,
});
export const StampEntry = IDL.Record({
  'source' : IDL.Text,
  'timestamp' : Time,
});
export const LoyaltyResponse = IDL.Record({
  'vouchers' : IDL.Vec(Voucher),
  'stampHistory' : IDL.Vec(StampEntry),
  'stampCount' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStamp' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUsersLoyaltyData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, LoyaltyResponse))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserLoyaltyData' : IDL.Func([], [LoyaltyResponse], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemVoucher' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Voucher = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'redeemed' : IDL.Bool,
  });
  const StampEntry = IDL.Record({ 'source' : IDL.Text, 'timestamp' : Time });
  const LoyaltyResponse = IDL.Record({
    'vouchers' : IDL.Vec(Voucher),
    'stampHistory' : IDL.Vec(StampEntry),
    'stampCount' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStamp' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUsersLoyaltyData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, LoyaltyResponse))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserLoyaltyData' : IDL.Func([], [LoyaltyResponse], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemVoucher' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };